### ISSUE TITLE
Search specific gene in heatmap

### ISSUE THREAD

**Issue by sanjaysingh765** [skutac/InCHlib.js#17]
Hi,
Thanks for creating this nice tool. Is it possible to search the heatmap for one or more genes together similar to clustergrammer? Thanks

**Comment by skutac** [comment]
Hi,
yes, you can do that by using the highlight_rows method (see. http://openscreen.cz/software/inchlib/examples/19). You can also set a color scale which will be used for the highlighting through the highlight_colors settings attribute.

Best,
C.
