### ISSUE TITLE
Redraw graph after container width change

### ISSUE THREAD

**Issue by Mesya82** [skutac/InCHlib.js#20]
Case:
I have Inchlib loaded in container that can change it's width dynamically. Inchlib's width property is set as default - null, which I assume, means that it will take all available width in container which is exactly what I need.

Expected:
When my container width changed I trigger some inchlib method(draw or redraw) which will redraw graph and fill out new free space.

Actual:
Nor draw nor redraw is not changing graph width unless I manually provide some specific width which is not good approach in my case.

**Comment by skutac** [comment]
Hi Mesya,
good suggestion.

To the dev version of InCHlib, I've just added a dynamic width possibility (set by default {"width": "dynamic"}). Now, when the element is resized and the redraw() method is called, the width is automatically adjusted.

Best,
Ctibor

**Comment by Mesya82** [comment]
Where I can find this dev version?

**UPD:** Nvm, found it

**Comment by skutac** [comment]
FYI, the dev version uses the [Konva.js framework](https://konvajs.github.io/) - the successor of Kinetic.js.

**Comment by Mesya82** [comment]
Yes, I just got the error. Already installed Konva in project
