### ISSUE TITLE
Difficulties to make the dev version working

### ISSUE THREAD

**Issue by titiller** [skutac/InCHlib.js#27]
Hi, 

In 2022, even with lots of DataViz libraries out there, I'm still very keen on your great tool.
But I have to admit that it's getting pretty hard to get it working with all the changes brought on its dependencies and with the discontinuation of python2.

Using the same inputs files that used to work fine with v1.20, I am really struggling using dev versions (with python3 and Konva) with no success. 
Using python3 and inchlib_clust_dev.py, it seems that i managed to produce the json files with but i could not display its content on my html container using Konva and inchlib_dev.js : lots of Konva warnings in the console and no display.

Here are some warnings i get since i'm using Konva and the dev version of InCHlib : 
_**Konva warning: NaN is a not valid value for "fontSize" attribute. The value should be a number.**_
or
_**Konva warning: "2.65" is a not valid value for "value" attribute. The value should be a number.**_
or even 
_**Konva warning: The stage has 9 layers. Recommended maximum number of layers is 3-5. Adding more layers into the stage may drop the performance. Rethink your tree structure, you can use Konva.Group.**_

Finally it produces empty canvas as you can see in the following picture :
![Capture d’écran 2022-09-17 à 17 40 38](https://user-images.githubusercontent.com/28139200/190864997-5417e9ff-3cb6-4a52-91b8-fffa23f99d8e.png)

So i'm wondering if you are still willing to maintain this lib.  Can I expect an updated version, or am i condemned to freeze the dependencies versions of my project if i still want to use your JS library.

Anyway thanks a lot for your great work, and thank you in advance for your answer.

Best,
A.D

**Comment by skutac** [comment]
Hi A.D.,
I would like to roll out a new stable ver. of InCHlib, but I really struggle to find time to do that. However, I'm using the dev ver. in my projects without any major issues.

Could you share with me your data and your InCHlib settings object?

Best,
Ctibor

**Comment by titiller** [comment]
Hi Ctibor,

thank you very much for your prompt response. 
I totally understand that keeping an old project alive is pretty difficult.

After reading your answer, i doubled checked my InCHlib settings Object and obviously i forgot to update some attributes.

I finally got it to display using Konva version 1.7.*  (csv files and object settings provided)
But with Konva v2 and above, lots of warnings and even Js errors with non working features (dendrogramm highlight for instance) as of v8.
I suppose it's due to the lots of Konva changes that are not  taken into account in current inchlib_dev.js.

As i don't want to bother you more, i'll freeze my Konva version to the 1.7 for now.
I wish i could help, but my JS skills are limited.
I Hope you'll still find time to keep this excellent heatmap lib alive.

Thanks again for your time.

Best,
Anis.D


[inchlibDataExpression.csv](https://github.com/skutac/InCHlib.js/files/9599219/inchlibDataExpression.csv)
[inchlibMetadataCondition.csv](https://github.com/skutac/InCHlib.js/files/9599220/inchlibMetadataCondition.csv)
[inchlibSettings.txt](https://github.com/skutac/InCHlib.js/files/9599223/inchlibSettings.txt)
