### ISSUE TITLE
Overlapping rows for large max_row_height

### ISSUE THREAD

**Issue by JEFworks** [skutac/InCHlib.js#5]
Hi,

I'm trying to use InCHlib to visualize some heatmaps generated in R. I generate the dendrograms using hclust in R and convert it into the Json format that InCHlib uses. 

When I set max_row_height: 2, the following results:
![screen shot 2015-01-28 at 2 56 51 pm](https://cloud.githubusercontent.com/assets/8975944/5945590/b9bcebcc-a6fd-11e4-8dc0-ec7aedd01cb5.png)

But when I set max_row_height: 32, the rows overlap and become illegible:
![screen shot 2015-01-28 at 2 58 11 pm](https://cloud.githubusercontent.com/assets/8975944/5945592/bd4e2b02-a6fd-11e4-8c39-62ed17a6773b.png)

Is there some way around this issue? I can provide the Json files if that'd be helpful.

Thank you!

Best,
Jean

**Comment by skutac** [comment]
Hi Jean,
that is quite strange. I've tried it myself and it seems ok:

![max_row_height_test](https://cloud.githubusercontent.com/assets/252871/5955263/6b12630e-a7a1-11e4-8bb0-2c6b8a6b23a7.png)

Please could you send me the json file and possibly the source data so I can look into it?

I've noticed that there can be some issues with different combinations of possible size attributes (max_row_height, max_height etc.) and I should also a little bit improve the margins of header and column metadata for larger sizes, but in neither case it should end up as in your screenshots.

Best,
Ctibor

**Comment by skutac** [comment]
Oh, you can send me the files to ctibor.skuta(at)img.cas.cz.

Best,
Ctibor

**Comment by JEFworks** [comment]
Thanks! Will do. I'd be happy to share my Rscripts as well to make InCHlib more accessible to R users.

**Comment by skutac** [comment]
That would be great. I'm sure a lot of people would appreciate it.

**Comment by JEFworks** [comment]
Fixed! Code updated in my fork if you're curious. Thanks for the help!

**Comment by skutac** [comment]
Great! I'll look at it, but to be true I'm not much familiar with R (I've used it few times, but I felt very inefficient :-)).
