### ISSUE TITLE
Toggling features

### ISSUE THREAD

**Issue by JEFworks** [skutac/InCHlib.js#7]
How can I toggle features such as the distance bar and allowing the users to adjust color settings? Can these be available as options?

**Comment by skutac** [comment]
Good idea, I will add it to the next release.

**Comment by JEFworks** [comment]
Awesome, thanks! Looking forward to it.

**Comment by skutac** [comment]
Navigation toggle option added to InChlib.

Default settings:

"navigation_toggle": {"color_scale": true, "distance_scale": true, "export_button": true, "filter_button": true, "hint_button": true}
