### ISSUE TITLE
Alternative data values

### ISSUE THREAD

**Issue by mitsiask** [skutac/InCHlib.js#8]
Greetings,

Congrats for this great project.
I have a question for you:

Many times, for better visualization reasons, normalized data values are provided  for clustering.

After the clustering, some users would like to view the unormalized data instead of the data values that were provided for clustering.

Does inchlib offer such functionality? Displaying alternative values for the clustered data by providing an additional data file as input?

Thanks in advance,
Dimitris

**Comment by skutac** [comment]
Hi Dimitris,
there are actually two possibilities:
1. If you use [inchlib_clust](http://openscreen.cz/software/inchlib/inchlib_clust) for the preparation of the [data for inchlib](http://openscreen.cz/software/inchlib/input_format), you can normalize the data before clustering (-n argument) but write the original data to the heatmap (-wo argument). In this case the heatmap will be colored according to the original values (column-wise or for the whole heatmap, your choice).
2. If you want to use different normalization than the one implemented in inchlib_clust, you can put the original values in the alternative_data section (-ad /path/to/alternative_data_file.csv) in the inchlib input file and then set the alternative_data option to true ("alternative_data": true). The alternative data section looks like this: {leaf_id_1: ["val_1", "val_2", .... "val_n"], leaf_id_2: ... }. In this case the heatmap will be colored using the normalized values but alternative data will be displayed. The length of data and alternative data arrays must be equal. This feature is so far implemented only in the dev version of [inchlib](https://github.com/skutac/InCHlib.js/blob/master/inchlib_dev.js)/[inchlib_clust](https://github.com/skutac/InCHlib.js/blob/master/inchlib_clust/inchlib_clust_dev.py), so presently you won't find it on the [official InCHlib pages](http://openscreen.cz/software/inchlib/home/).

New version of InCHlib (with updated examples and docs) should be hopefully out in March.

Best,
Ctibor

**Comment by mitsiask** [comment]
Perfect, I will use the dev version then.

Thank you again,
Dimitris

**Comment by skutac** [comment]
Great.

Let me know if anything is not working. So far this feature has not been tested much. ;-)

Best,
Ctibor
